language: node_js
node_js:
  - "8.11.1"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

before_deploy:
  - cd functions && npm install && npm run build
  - cd ..

deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change